#!/bin/bash

echo "🔍 Verificando logs do webhook-receiver..."
echo "📅 Data/hora atual: $(date)"
echo ""
echo "🌐 Acesse o dashboard do Supabase:"
echo "https://supabase.com/dashboard/project/svkgfvfhmngcvfsjpero/functions/webhook-receiver/logs"
echo ""
echo "🔍 Procure por logs com:"
echo "- 🔥 [req_] - Logs de debug detalhados"
echo "- WEBHOOK_LOG: - Logs estruturados em JSON"
echo "- Timestamp recente (últimos 5 minutos)"
echo ""
echo "📊 Se não aparecerem logs novos, pode ser:"
echo "1. ⏰ Delay na exibição dos logs (aguarde 1-2 minutos)"
echo "2. 🚫 Filtros ativos no dashboard (remova filtros)"
echo "3. 🔄 Cache do browser (force refresh com Ctrl+F5)"
echo "4. 📡 Problema de conectividade com o webhook"
echo ""
echo "🧪 Para testar novamente:"
echo "curl -X POST https://svkgfvfhmngcvfsjpero.supabase.co/functions/v1/webhook-receiver \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"instance\": \"chat saira\", \"data\": {\"key\": {\"remoteJid\": \"556492019427@s.whatsapp.net\", \"fromMe\": false, \"id\": \"test_$(date +%s)\"}, \"message\": {\"conversation\": \"Teste $(date)\"}, \"messageTimestamp\": $(date +%s), \"pushName\": \"Teste\"}}'"