version: '3.8'

services:
  saira-frontend:
    image: saira-frontend:latest
    networks:
      - traefik-public
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: stop-first
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      labels:
        # Traefik configuration
        - "traefik.enable=true"
        - "traefik.http.routers.saira-frontend.rule=Host(`saira.insignemarketing.com.br`)"
        - "traefik.http.routers.saira-frontend.entrypoints=websecure"
        - "traefik.http.routers.saira-frontend.tls.certresolver=letsencrypt"
        - "traefik.http.services.saira-frontend.loadbalancer.server.port=80"
        
        # HTTP to HTTPS redirect
        - "traefik.http.routers.saira-frontend-http.rule=Host(`saira.insignemarketing.com.br`)"
        - "traefik.http.routers.saira-frontend-http.entrypoints=web"
        - "traefik.http.routers.saira-frontend-http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
        
        # Load balancer configuration
        - "traefik.http.services.saira-frontend.loadbalancer.healthcheck.path=/health"
        - "traefik.http.services.saira-frontend.loadbalancer.healthcheck.interval=30s"
        
        # Security headers
        - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
        - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
        - "traefik.http.routers.saira-frontend.middlewares=security-headers"
        
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  traefik-public:
    external: true