
import { Conversation } from './types';

export const mockConversations: Conversation[] = [
  {
    id: '1',
    name: 'João Silva',
    phone: '+55 11 98765-4321',
    lastMessage: 'Posso retirar meu remédio hoje?',
    time: '10:42',
    unread: 2,
    status: 'read',
    tags: ['uso contínuo'],
  },
  {
    id: '2',
    name: 'Maria Oliveira',
    phone: '+55 11 91234-5678',
    lastMessage: 'Obrigada pelo atendimento!',
    time: '09:15',
    unread: 0,
    status: 'delivered',
    tags: ['diabético'],
  },
  {
    id: '3',
    name: 'Carlos Mendes',
    phone: '+55 11 99876-5432',
    lastMessage: 'Vocês têm Losartana em estoque?',
    time: 'Ontem',
    unread: 0,
    status: 'read',
    tags: ['hipertenso', 'uso contínuo'],
  },
  {
    id: '4',
    name: 'Ana Beatriz',
    phone: '+55 11 97654-3210',
    lastMessage: 'Preciso do anticoncepcional...',
    time: 'Ontem',
    unread: 0,
    status: 'sent',
    tags: ['uso contínuo'],
  },
  {
    id: '5',
    name: 'Pedro Santos',
    phone: '+55 11 98877-6655',
    lastMessage: 'O antibiótico está disponível?',
    time: '25/04',
    unread: 0,
    status: 'pending',
    tags: ['antibiótico'],
  },
];
